export const AuthType = {
    BEFORE_STATE: "BEFORE_STATE",
    AUTHENTICATED: "AUTHENTICATED",
    LOGIN_INVALID: "LOGIN_INVALID",
    REGISTERED: "REGISTERED",
    ERROR_REGISTER: "ERROR_REGISTER",
    FAIL_REGISTER: "FAIL_REGISTER"
}