export const PostType = {
    BEFORE_STATE: "BEFORE_STATE",
    SET_LOADING: "SET_LOADING",
    STOP_LOADING: "STOP_LOADING",
    SET_PAGE: "SET_PAGE",
    SET_DATA: "SET_DATA",
    CHANGE_CATEGORY: "CHANGE_CATEGORY",
    CREATED: "CREATED",
    CREATE_FAIL: "CREATE_FAIL",
    ERROR_CREATE: "ERROR_CREATE"
}