export const PostType = {
    BEFORE_STATE: "BEFORE_STATE",
    SET_LOADING: "SET_LOADING",
    STOP_LOADING: "STOP_LOADING",
    SET_PAGE: "SET_PAGE",
    SET_DATA: "SET_DATA",
    CHANGE_CATEGORY: "CHANGE_CATEGORY"
}