export const ProfileType = {
    BEFORE_STATE: "BEFORE_STATE",
    SET_LOADING: "SET_LOADING",
    STOP_LOADING: "STOP_LOADING",
    SET_PROFILE: "SET_PROFILE",
    SET_POSTS: "SET_POSTS",
    SET_PAGE: "SET_PAGE",
}